### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by edisonlee55** [arcusmaximus/YTSubConverter#1]

**Comment by edisonlee55** [comment]
Because mono current can't run WinForms apps in x64 mode on macOS.

I have ported YTSubConverter to macOS by using the [filipnavara/mac-playground](https://github.com/emclient/mac-playground) workaround mentioned in mono/mono#6701.

---

**macOS version repo: [edisonlee55/YTSubConverterMac](https://github.com/edisonlee55/YTSubConverterMac)**

**[Download](https://github.com/edisonlee55/YTSubConverterMac/releases/latest/download/YTSubConverterMac.app.zip)**

---

**Screenshot**
<img width="912" alt="YTSubConverterMac-Screenshot" src="https://user-images.githubusercontent.com/5277788/82869269-8aa57f00-9f60-11ea-9e28-3ad88658389c.png">

---

**Unimplemented function:**
- Text Preview Box (which uses `Mono.WebBrowser`)

**Comment by CarbonY26** [comment]
Thanks for this Mac build.

**Comment by arcusmaximus** [comment]
It took long enough, but I'm happy to announce that YTSubConverter is now officially available for macOS. Everything is there: visual subtitle preview, multilanguage UI, and "even" a native color picker rather than an emulation of the Windows one.

![image](https://user-images.githubusercontent.com/133129/135145873-f9043a7b-c1b2-4870-aed5-1de285580c45.png)

You can find the .dmg on the [Releases](https://github.com/arcusmaximus/YTSubConverter/releases/tag/1.5.3) page.
