### ISSUE TITLE
It seems that YouTube's messing with the captions system

### ISSUE THREAD

**Issue by sf365d** [arcusmaximus/YTSubConverter#12]
![YT](https://user-images.githubusercontent.com/60170282/72869832-007ead00-3d19-11ea-9018-e7c22bc32128.PNG)
I don't know if this is just a temporary or not, but as you can see on the image above, the transparencies didn't work and apparently the colors too.

**Comment by arcusmaximus** [comment]
This is indeed YouTube's fault. They recently introduced a new subtitle format with great features such as:
* A larger file size than before,
* no new functionality,
* limitation of the available colors from 16 million to 8,
* incorrect handling of even those few colors,
* and incorrect handling of transparency.

The result of the 4th item is that in order to get red text, you now have to specify dark green in the subtitle file. However, this only works on PC; on mobile you'll get, well, dark green text. Because of this inconsistency, I can't even make a version of YTSubConverter that unborks the colors on PC because it'll bork the colors on mobile instead.

All I can do is give some recommendations for while the bug is around:
* Don't use any colors other than black and white.
* Don't use an alpha of 0 - always use at least 1.

In the meantime, feel free to upvote this Reddit post so YouTube developers might see it: https://www.reddit.com/r/youtube/comments/es4yd2/misc_fd_stylized_captions_are_now_broken/

**Comment by arcusmaximus** [comment]
Shortly after writing this post, YouTube incredibly rolled back the new format, fixing the bugs! All subtitles are now back to how they used to be.
