### ISSUE TITLE
Big .ass File Will Cause Program OOM

### ISSUE THREAD

**Issue by temporary-only** [arcusmaximus/YTSubConverter#20]
Software Version: 1.4.3
Operating System: Windows 10 19041.388
Available Memory: 25.1 GB
[.assFile](https://github.com/arcusmaximus/YTSubConverter/files/4988572/testFile.zip): 22.7 MB

Exhaustive Error: Failed to load file: Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by arcusmaximus** [comment]
YTSubConverter is not meant to work for any .ass file - it's only meant for files that were specifically created with YouTube in mind. This is clearly not the case for the file you attached.

If you want to create a YouTube video with these specific subtitles, I'd recommend burning them into the video (hardsubbing) rather than trying to convert them to YouTube captions (softsubbing). Here's a guide on how to do that:
https://www.reddit.com/r/PleX/comments/4fnus7/hardsub_ass_file_into_any_video_just_using_vlc_221/

**Comment by temporary-only** [comment]
K, really appreciate for the useful reference you provided.
