### ISSUE TITLE
Help :c

### ISSUE THREAD

**Issue by Vestiary** [arcusmaximus/YTSubConverter#3]
could you help me, when I convert the subtitles and upload them to youtube I get black, how can I fix it?
![image](https://user-images.githubusercontent.com/54251440/63231460-03b1c200-c1ea-11e9-88df-697661784273.png)

**Comment by arcusmaximus** [comment]
If you're using a color tag (\c or \1c) rather than a style, please check it's formatted correctly. YTSubConverter is currently more strict than Aegisub, so while e.g. \cFF00 works in Aegisub, you have to use the full \c&H00FF00& for YTSubConverter.

If it is correct, please attach your .ass file so I can take a look.

**Comment by arcusmaximus** [comment]
Any update? If I don't hear back from you, I won't be able to help and I'll have to close this ticket.

**Comment by Vestiary** [comment]
Yes Thanks, Work Fine :D

**Comment by arcusmaximus** [comment]
Good to hear :)

**Comment by Vestiary** [comment]
Thanks For The Help Bruh :)
