### ISSUE TITLE
Default youtube style

### ISSUE THREAD

**Issue by DrawTR** [arcusmaximus/YTSubConverter#35]
Hi, is it possible to recreate the default youtube subtitle style in this program/aegisub? Or would I have to mess with the settings to find it manually

**Comment by arcusmaximus** [comment]
The default background color for YouTube subtitles is #080808 with alpha 192.

**Comment by DrawTR** [comment]
Ah, sorry, @arcusmaximus. I missed this response! I was just wondering if there was a way to remove any extra styling information while retaining using a .ass file. Not sure if that makes sense, I can elaborate if needed, I'm just looking to have a normal stylized sub but while retaining the ability to use other formatting features such as italics and bold.

**Comment by arcusmaximus** [comment]
YTSubConverter always writes color information to the .ytt file, even if the colors are the same as the YouTube defaults. If you don't want that, you'll have to edit the .ytt in a text editor and manually remove all the `fc`/`fo`/`bg`/`bo` attributes from the <pen> elements.

**Comment by DrawTR** [comment]
Ah, that's a little annoying. Do you know of any alternative formats that support markup but not styling?

**Comment by arcusmaximus** [comment]
The SRV3 format which YTSubConverter produces can be color-neutral through the exclusion of the previously mentioned color attributes. The other formats that YouTube "supports" are listed here:
https://support.google.com/youtube/answer/2734698?hl=en#zippy=%2Cadvanced-file-formats

I say "supports" in quotes because all these formats have their share of bugs and limitations.

For starters, all formats have a bug involving subtitles with mixed markup (e.g. one part that's bold and one part that isn't). See this file for details:
https://github.com/arcusmaximus/YTSubConverter/blob/3455abe39138348283bc12f9ad2f5b94e2115e61/ytt.ytt#L114 (YTSubConverter automatically works around this and other bugs for you)

The most straightforward choice for a simple format with minimal markup would be SRT. However, YouTube doesn't recognize the markup and makes it part of the subtitle text.

With DFXP you can get positioning and markup on YouTube, but only in one very specific way that may not match the way your conversion program does it.

With WebVTT you can also get positioning, but it's notoriously buggy - the subtitles often wind up in the wrong place.

That leaves the TV broadcast formats, but those only support putting subtitles in the corners of the video, not at arbitrary locations.

Finally, there's actually a reason YTSubConverter always writes alpha information. Try opening a YouTube video with normal unstyled subtitles and pressing O; you'll notice that the text becomes darker and harder to read. This is YouTube's keyboard shortcut for changing subtitle Opacity, which seems innocuous at first sight - in practice, however, my experience is that most people trigger it by accident and don't know how to change it back. By always writing alpha information to the .ytt file, this accidental opacity change is overriden, keeping subtitles readable.

Similarly, the converter always writes color information - even for white text where it's seemingly unnecessary - to work around a bug in the Android app that happens when mixing colors. Not immediately relevant for you as you won't be using colors, but I hope this explains why the converter works the way it does.

**Comment by DrawTR** [comment]
Thank you for the response, I really appreciate the help.

I ended up messing around and making a style that's as similar to the YouTube default as possible - it's not perfect, but I think it's the best you can do with the limitations of the styles. I did end up trying some other formats but none really have the customizability of .ytt so I think I'll just stick with that. Thanks again!

**Comment by arcusmaximus** [comment]
Glad to hear. As mentioned in my first comment, you can create a perfect replica of the YouTube default by using white text and a background of # 080808 with alpha 192 (or 256 - 192 = 64 in Aegisub, so `{\3c&H080808&\3a&H40&}`).
