### ISSUE TITLE
any format -> srv3 conversion not working correctly at all

### ISSUE THREAD

**Issue by ccccmark** [arcusmaximus/YTSubConverter#43]
I just noticed that if I download the yt-dlp srv3 sub format, subtitles works fine, but I try to convert from any other format to srv3, it messes it up, is there a way to make the conversion similar to the yt-dlp one?

**Comment by arcusmaximus** [comment]
YTSubConverter is primarily meant for converting from .ass to .ytt (.srv3). Converting from other formats like .srt should be possible too, but has little use because (unlike .ass) you can simply upload those to YouTube directly without any conversion.

Could you give some more details on what exactly you're trying to achieve? Like which file you're trying to convert, and what you intend to do with the result.

**Comment by ccccmark** [comment]
Well, I am currently trying to achieve something like premiere videos
archiving (because I think that the chat replay for premiere videos on YT
sucks), converting from .ass to .srv3 so more players could actually handle
them without any problem, using yt-dlp subtitle download works fine, but
conversion from ass to srv3 using the program just messes it up, like not
jumping lines or something similar.

**Comment by arcusmaximus** [comment]
I'm afraid that converting from .ass to .srv3 when downloading subtitles seems a bit backwards. Normally this is something you do when uploading.

.srv3 is YouTube's native subtitle format. If you archive a video and download its subtitles without any conversion, you'll get an .srv3 file. Because this format was created for YouTube and is not used anywhere else, most (if not all) video player applications can't handle it. What they can handle is formats like .ass and .srt.

This means that, if you want to download a YouTube video for local viewing, you should be converting from .srv3 to .ass, not the other way around.

Please see the manual section about reverse conversion for details:
https://github.com/arcusmaximus/YTSubConverter#reverse-conversion

**Comment by ccccmark** [comment]
Oke, understood, closing
