### ISSUE TITLE
Is there any good way to test on mobile phone?

### ISSUE THREAD

**Issue by tran-huynh-minh-ngoc** [arcusmaximus/YTSubConverter#54]
I made some subtitles and while they are looking good on PC, they are horrible on Android (and presumably iOS). There are issues (font size, line wrap, position) that I didn't think about on Android.

So is there any way I can quickly test the subtitles on Android? Uploading onto my own channel is pretty cumbersome.

**Comment by arcusmaximus** [comment]
With old versions of Android (and the YouTube app?), you could use an Android emulator for this: run Fiddler on your PC, install its certificate into the emulator, set it as the proxy server, and run the app. With more recent versions, however, this sadly doesn't seem to work anymore (probably due to certificate pinning).
