### ISSUE TITLE
How do I build on Linux for Linux?

### ISSUE THREAD

**Issue by AtticFinder65536** [arcusmaximus/YTSubConverter#63]
I'd like to create my own build for this program, but I'm not really familiar with dotnet/mono. I tried multiple methods using `msbuild` and `dotnet publish` but I can't get it to build, so I'd like to know what the expected way to build this would be.

**Comment by arcusmaximus** [comment]
`dotnet` indeed won't work as that's for .NET Core rather than .NET Framework (which is what Mono emulates). You can build YTSubConverter by installing MonoDevelop, opening the .sln file, and pressing F5. There's probably a way to do it from the command line, but I'm too spoiled by IDEs to figure that out :)
