### ISSUE TITLE
Questions regarding the generated subtitles

### ISSUE THREAD

**Issue by 00Creamy** [arcusmaximus/YTSubConverter#73]
This is not an issue but rather a question
Why does the generated subtitles doubles and put some zero width spaces on the start and the end?

**Comment by arcusmaximus** [comment]
Subtitle duplication happens when your .ass style has both a shadow and an outline. YouTube subtitles can't have both at the same time, so YTSubConverter creates one with a shadow and one with an outline and makes them overlap.

Another reason it can happen is when you have dark text. This is explained in the readme.

Zero-width spaces are used for working around all kinds of YouTube bugs. I wish they weren't necessary, but they are - without them, even simple stuff like making one word in a sentence bold would not be possible, because YouTube's subtitle code is just that buggy.
